disabled_rules:
  - line_length
  - type_body_length
  - file_length
  - valid_docs
  - legacy_constructor
  - cyclomatic_complexity
  - legacy_cggeometry_functions
  - function_parameter_count
  - conditional_binding_cascade
  - variable_name
  - closure_parameter_position
  - todo
  - operator_whitespace
excluded:
function_body_length:
  - 200
  - 300
variable_name:
  min_length:
    warning: 2